const { chromium, setup, watch, SHOTS } = require("./harness");
let ok = 0, bad = 0; const errors = [];
const check = (c, w) => { if (c) ok++; else { bad++; console.log("  FAIL:", w); } };
(async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport:{ width:1280, height:900 } });
  await setup(ctx);
  const p = await ctx.newPage(); watch(p, errors, "misc");
  await p.goto("https://browser.example/whatsnew.html"); await p.waitForTimeout(600);
  check(await p.textContent("#count") === "458", "458 features counted");
  check(await p.locator(".f").count() === 458, "458 cards");
  check(/3\.5 · Phantom calendar/.test(await p.textContent("#out h2")), "3.5 group first");
  await p.fill("#q", "breakout"); await p.waitForTimeout(100);
  check(await p.locator(".f:not(.hide)").count() >= 1, "search finds Breakout");
  await p.fill("#q", ""); await p.waitForTimeout(1500); await p.screenshot({ path:SHOTS + "whatsnew.png" });
  await p.goto("https://browser.example/settings.html#x3"); await p.waitForTimeout(700);
  await p.screenshot({ path:SHOTS + "settings-x3.png" });
  check(await p.locator("#x3").count() === 1 || await p.locator("[id=x3]").count() === 1, "3.0 section present");
  await p.evaluate(() => { __sent.length = 0; });
  const sw = p.locator('[data-k="xClock"], #xClock').first();
  await sw.scrollIntoViewIfNeeded(); await sw.click(); await p.waitForTimeout(300);
  check(await p.evaluate(() => __sent.some(m => /xClock/.test(m)) || /"xClock":true/.test(localStorage.getItem("wsb.settings") || "")), "clock switch saves");
  await p.selectOption("#searchEngine", "ecosia"); await p.waitForTimeout(200);
  check(await p.evaluate(() => /"search":"ecosia"/.test(localStorage.getItem("wsb.settings") || "") || __sent.some(m => /ecosia/.test(m))), "new engine selectable");
  await p.fill("#xCustomUrl", "not a url"); await p.press("#xCustomUrl", "Tab"); await p.waitForTimeout(200);
  check(!/not a url/.test(await p.evaluate(() => localStorage.getItem("wsb.settings") || "")), "bad engine address refused");
  console.log("\nchecks passed:", ok, "failed:", bad);
  console.log("errors:", errors.length ? "\n  " + errors.join("\n  ") : "none");
  await browser.close();
})().catch(e => { console.error("CRASH", e); process.exit(1); });
