"3.0 · Address bar answers": [
  ["BMI", "Body mass index from your weight and height, in kg and cm or pounds and feet.", "Address bar: bmi 70kg 175cm"],
  ["Exact age", "Years, months and days since a date, and how long until the next birthday.", "Address bar: age 1990-05-14"],
  ["Loan payments", "The monthly payment, total paid and interest for a loan or mortgage.", "Address bar: loan 250k at 4.5% for 30 years"],
  ["Savings that grow", "What money becomes with interest, with an optional amount added each month.", "Address bar: 10000 at 5% for 10 years plus 200 a month"],
  ["Time between two times", "Hours and minutes from one clock time to another, even past midnight.", "Address bar: 9:15am to 5:40pm"],
  ["Roman numerals", "Turn a number into Roman numerals and back.", "Address bar: 2026 in roman, roman MMXXVI"],
  ["Numbers in words", "Any number written out, up to the quadrillions.", "Address bar: 1234567 in words"],
  ["Base64", "Encode text as Base64, or decode it.", "Address bar: base64 encode: hello"],
  ["URL encoding", "Make text safe for a web address, or turn %20 and friends back into text.", "Address bar: url decode a%20b"],
  ["SHA hashes", "SHA-1, SHA-256, SHA-384 or SHA-512 of any text.", "Address bar: sha256: your text"],
  ["Pick one", "Can't decide? It picks one at random.", "Address bar: pick: pizza, tacos, sushi"],
  ["Placeholder text", "Lorem ipsum by the word, sentence or paragraph, ready to paste.", "Address bar: lorem 3 paragraphs"],
  ["Unix time", "The timestamp now, a timestamp as a date, or a date as a timestamp.", "Address bar: unix, 1700000000 unix"],
  ["Week number and year progress", "Today's week number and how much of the year has gone.", "Address bar: week number, year progress"],
  ["Leap years", "Whether a year is a leap year, and when the next one is.", "Address bar: is 2028 a leap year"],
  ["Prime numbers", "Check whether a number is prime, or break it into prime factors.", "Address bar: is 97 prime, factors of 360"],
  ["GCD and LCM", "Greatest common divisor and least common multiple of a list of numbers.", "Address bar: gcd 12 18, lcm 4 6 10"],
  ["List statistics", "Sum, average, median, smallest, largest and range of a list of numbers.", "Address bar: average 3, 7, 12"],
  ["Running pace", "Pace per km and per mile, and your speed.", "Address bar: pace 10 km in 52:30"],
  ["Download time", "How long a file takes at a given connection speed.", "Address bar: download 4 GB at 100 mbps"],
  ["Aspect ratios", "The ratio of any size, or the size for a ratio at a width or height.", "Address bar: 1920x1080 ratio, 16:9 at 1440 wide"],
  ["Screen sharpness", "Pixels per inch for a screen size and resolution.", "Address bar: ppi 2560x1440 27"],
  ["Emoji search", "Find an emoji by name and copy it.", "Address bar: :fire or emoji: heart"],
  ["Morse code", "Text to Morse code and back again.", "Address bar: morse: SOS"],
  ["Text as binary", "Any text as ones and zeros (UTF-8), and back.", "Address bar: binary: hi"],
  ["Character info", "What a character is: its code point, HTML and CSS codes and UTF-8 bytes.", "Address bar: unicode é"],
  ["Upside-down text", "Flip any text upside down to paste somewhere fun.", "Address bar: upside down hello"],
  ["Text faces", "Shrug, table flip, bear and more, ready to copy.", "Address bar: shrug, table flip"],
  ["QR code for any text", "A QR code for a note, a Wi-Fi password or a link.", "Address bar: qr: your text"],
  ["Add a to-do", "Add to your to-do list without opening it.", "Address bar: todo: buy milk"],
  ["Quick pages", "Jump to History, Settings, Games, the sidebar tools and more by name.", "Address bar: @ and a name, like @settings"],
  ["Synonyms and rhymes", "Other words for a word, and words that rhyme with it.", "Address bar: synonyms for happy, rhymes with moon"]
],
"3.0 · Search": [
  ["Six more search engines", "Ecosia, Qwant, Kagi, Yahoo, Mojeek and Yandex.", "Settings → Search engine"],
  ["Your own search engine", "Use any site's search as your engine: paste its address with %s where the words go.", "Settings → Webs 3.0 extras"],
  ["More engines on the new tab page", "The search box's engine picker has the new engines and yours too.", "New tab → search box"],
  ["Bangs for video, music and social sites", "!yt, !sp, !tt, !r, !x, !pin and !imdb search YouTube, Spotify, TikTok, Reddit, X, Pinterest and IMDb.", "Address bar: !yt cat videos"],
  ["Bangs for shopping, maps, pictures and news", "!a Amazon, !eb eBay, !m Google Maps, !i Google Images and !n Google News.", "Address bar: !m coffee near me"],
  ["Bangs for developers and research", "!gh, !so, !mdn, !npm, !wa, !sch, !wb and !tr: GitHub, Stack Overflow, MDN, npm, Wolfram Alpha, Scholar, the Wayback Machine and Translate.", "Address bar: !mdn flexbox"],
  ["Bangs for every engine", "!eco, !q, !k, !y, !mj, !ya and !my send one search to another engine.", "Address bar: !k your search"]
],
"3.0 · Tabs": [
  ["Rename a tab", "Give a tab your own name. It keeps it after a restart.", "Right-click a tab → Rename tab"],
  ["Lock a tab", "A locked tab can't be closed by accident.", "Right-click a tab → Lock tab"],
  ["Self-closing tabs", "Close a tab by itself in 5 minutes to 2 hours.", "Right-click a tab → Close this tab in…"],
  ["Move to the start or end", "Send a tab to either end of the strip.", "Right-click a tab"],
  ["Close all tabs from a site", "Every tab from the same site, in one go.", "Right-click a tab"],
  ["Back to the last tab", "Jump to the tab you were just on, and back again.", "Alt+`"],
  ["Sort tabs", "By name, or the ones you used last first.", "Ctrl+Shift+P → Sort tabs"],
  ["Reload every tab", "Refresh all open pages at once.", "Ctrl+Shift+P → Reload every tab"],
  ["Mute or unmute every tab", "Silence the whole browser, or let it play again.", "Ctrl+Shift+P → Mute every tab"],
  ["Save open tabs to a file", "A page of links to every open tab, to keep or share.", "Ctrl+Shift+P → Save open tabs"],
  ["Open a list of links", "Paste any text with links in it and open them all.", "Ctrl+Shift+P → Open a list of links"],
  ["Surprise me", "Opens one of your bookmarks at random.", "Ctrl+Shift+P → Surprise me"],
  ["Unread dots", "Tabs opened in the background get a dot until you look at them.", "Settings → Webs 3.0 extras"],
  ["Undo after closing", "A short note with an Undo button each time you close a tab.", "Settings → Webs 3.0 extras"],
  ["Tab numbers", "A small number on the first eight tabs and the last, for Ctrl+1 to Ctrl+9.", "Settings → Webs 3.0 extras"],
  ["Tab counter", "How many tabs are open; click it for the tab overview.", "Settings → Webs 3.0 extras"],
  ["Close buttons on hover", "The ✕ on the tab you're on stays hidden until you point at it.", "Settings → Webs 3.0 extras"],
  ["Big tabs", "Taller tabs, easier to hit on a touch screen.", "Settings → Webs 3.0 extras"],
  ["Icon-only tabs", "Every tab as small as a pinned one, for when you have lots.", "Settings → Webs 3.0 extras"],
  ["Narrow or wide tabs", "Pick how wide tabs are.", "Settings → Webs 3.0 extras → Tab width"]
],
"3.0 · Toolbar and looks": [
  ["Clock in the tab strip", "The time beside your tabs; click it for alarms.", "Settings → Webs 3.0 extras"],
  ["Date beside the clock", "The day and date next to the time.", "Settings → Webs 3.0 extras"],
  ["Battery level", "On laptops and tablets, with a warning color when it's low.", "Settings → Webs 3.0 extras"],
  ["Corner styles", "Square or extra-round tabs, buttons and panels.", "Settings → Webs 3.0 extras → Corners"],
  ["Interface fonts", "Bahnschrift, Verdana, Georgia, Cascadia Code or Comic Sans for the browser itself.", "Settings → Webs 3.0 extras → Interface font"],
  ["Rainbow loading bar", "The loading bar runs through every color.", "Settings → Webs 3.0 extras"],
  ["Glowing active tab", "The tab you're on glows softly in your accent color.", "Settings → Webs 3.0 extras"],
  ["Color-cycling accent", "The accent color slowly travels around the rainbow.", "Settings → Webs 3.0 extras"]
],
"3.0 · Reading tools": [
  ["Reading guide", "A bright band follows your pointer and dims the rest, so you don't lose your line.", "Menu → More page tools, or Alt+Shift+R"],
  ["Bionic reading", "The start of each word in bold, to read faster.", "Menu → More page tools, or Alt+Shift+B"],
  ["Spotlight", "Everything goes dark except a circle around your pointer.", "Menu → More page tools, or Alt+Shift+X"],
  ["Big text under the pointer", "Whatever text you point at, shown large in a box.", "Menu → More page tools"],
  ["Speed reader", "The article one word at a time, at the speed you pick.", "Menu → More page tools, or Alt+Shift+E"],
  ["Words and reading level", "How hard a page is to read, and the words it uses most.", "Menu → More page tools"],
  ["Highlight words", "Mark every place up to six words appear, each in its own color.", "Menu → More page tools"],
  ["Calm page", "Stops animations and moving things on a page.", "Menu → More page tools"],
  ["Open every folded section", "Expands all the collapsed answers and details at once.", "Menu → More page tools"],
  ["Text only", "Hide the pictures on a page, then show them again.", "Menu → More page tools"]
],
"3.0 · Find things on a page": [
  ["All pictures", "Every picture on the page in a grid, biggest first, with sizes.", "Menu → More page tools, or Alt+Shift+G"],
  ["All links", "Every link with a filter, and only the ones to other sites if you like.", "Menu → More page tools, or Alt+Shift+U"],
  ["Emails and phone numbers", "Contact details on a page, each with a Copy button.", "Menu → More page tools"],
  ["Find and replace", "Change words on a page, for a screenshot or a print.", "Menu → More page tools"],
  ["Show passwords", "See what you typed in password boxes.", "Menu → More page tools"],
  ["Picture zoom on hover", "Point at a small picture to see it big.", "Menu → More page tools, or Alt+Shift+Z"]
],
"3.0 · Save and share": [
  ["Save as Markdown", "The article as a tidy Markdown file, links and tables included.", "Menu → More page tools"],
  ["Tables to a spreadsheet", "Every table on a page saved as a CSV file for Excel.", "Menu → More page tools"],
  ["Copy all the text", "The page's text on the clipboard.", "Menu → More page tools"],
  ["Save the text", "The page's text as a .txt file.", "Menu → More page tools"],
  ["Copy the title", "The page title on the clipboard.", "Menu → More page tools"],
  ["Email this page", "Starts an email with the title and link.", "Menu → More page tools"]
],
"3.0 · For designers": [
  ["Fonts on this page", "Every font a page uses, with a sample of each; click one to copy its name.", "Menu → More page tools"],
  ["Colors on this page", "The page's colors as swatches; copy one, or all of them as CSS.", "Menu → More page tools"],
  ["Accessibility check", "Missing picture descriptions, unlabeled buttons, low contrast and more.", "Menu → More page tools"],
  ["Layout grid", "A column grid over the page to check alignment.", "Menu → More page tools"]
],
"3.0 · Video": [
  ["Picture adjust", "Brightness, contrast, color and tint, and rotate or mirror a video.", "Menu → More page tools"],
  ["Frame by frame", "Step a paused video one frame back or forward.", "Alt+Shift+, and Alt+Shift+."]
],
"3.0 · Presenting": [
  ["Show the keys I press", "Keys appear on screen as you press them, for recording how-tos.", "Menu → More page tools"],
  ["Laser pointer", "A glowing red trail follows your pointer while you show a page.", "Menu → More page tools"]
],
"3.0 · The web": [
  ["Older versions of a page", "Open the page in the Wayback Machine.", "Menu → More page tools"],
  ["Save a copy at the Internet Archive", "Keep the page as it is today.", "Menu → More page tools"],
  ["Is it down for everyone?", "Check whether a site that won't load is down or just you.", "Menu → More page tools"],
  ["Search only this site", "Search inside the site you're on.", "Menu → More page tools"],
  ["Go up a level", "From a page to its section, and on up to the site.", "Menu → More page tools"],
  ["Site home page", "Straight to the front page of the site.", "Menu → More page tools"],
  ["Next or previous page number", "Moves through numbered pages by changing the number in the address.", "Menu → More page tools"],
  ["Translate into any of 20 languages", "Pick the language, not just your own.", "Menu → More page tools → Translate into"]
],
"3.0 · Just for fun": [
  ["Let it snow", "Snow falls over any page.", "Menu → More page tools"],
  ["Confetti", "A burst of confetti on any page.", "Menu → More page tools"],
  ["Disco colors", "The page's colors spin round.", "Menu → More page tools"],
  ["Flip the page", "Turn the whole page upside down.", "Menu → More page tools"],
  ["Gravity", "Everything on the page falls to the bottom.", "Menu → More page tools"]
],
"3.0 · Web page extras": [
  ["Reading progress bar", "A thin bar at the top of long pages shows how far you've read.", "Settings → Webs 3.0 extras"],
  ["Back to top button", "A button in the corner once you've scrolled down a long page.", "Settings → Webs 3.0 extras"],
  ["Picture zoom everywhere", "Picture zoom on hover on every site.", "Settings → Webs 3.0 extras"],
  ["Hide YouTube Shorts", "No Shorts shelves, Shorts tab or short videos in lists.", "Settings → Webs 3.0 extras"],
  ["Hide YouTube recommendations", "No home feed, side list or end screen, so you watch what you came for.", "Settings → Webs 3.0 extras"],
  ["Page tool shortcuts", "The Alt+Shift shortcuts work even while a web page has the keyboard.", "Settings → Webs 3.0 extras"]
],
"3.0 · Sidebar tools": [
  ["World clocks", "The time in any city, with the difference from yours.", "Sidebar → More → World clocks"],
  ["Sketchpad", "Draw in colors and sizes, then copy the picture. It stays until you clear it.", "Sidebar → More → Sketchpad"],
  ["Passphrase generator", "Easy-to-type passphrases of random words, and strong passwords with the options you pick.", "Sidebar → More → Passwords"],
  ["JSON formatter", "Format, check and shrink JSON.", "Sidebar → More → JSON"],
  ["Compare two texts", "See what changed between two versions of a text.", "Sidebar → More → Compare text"],
  ["Regex tester", "Try a pattern on some text and see every match.", "Sidebar → More → Regex tester"],
  ["Markdown preview", "Write Markdown and see it formatted as you type.", "Sidebar → More → Markdown"],
  ["Color palettes", "Palettes from one color, and a contrast check for text.", "Sidebar → More → Colors"],
  ["Breathing exercise", "A calm minute of guided breathing.", "Sidebar → More → Breathe"],
  ["Metronome", "Keep the beat, or tap to find a tempo.", "Sidebar → More → Metronome"],
  ["Decision wheel", "Spin a wheel of your choices.", "Sidebar → More → Decision wheel"],
  ["Tally counter", "Count anything with one click.", "Sidebar → More → Tally counter"],
  ["Price per unit", "Which pack is cheaper for what you get.", "Sidebar → More → Price per unit"]
],
"3.0 · New tab page": [
  ["Day and year progress", "How much of today, this week, this month and this year has gone.", "New tab → Customize"],
  ["Today's focus", "One thing you want to get done today.", "New tab → Customize"],
  ["Moon phase", "Tonight's moon and when the next full moon is.", "New tab → Customize"],
  ["World clocks widget", "Your favorite cities' times on the new tab page.", "New tab → Customize"],
  ["Water tracker", "Click a glass each time you drink, up to eight a day.", "New tab → Customize"],
  ["Screen time today", "How long you've browsed today and where you spent it.", "New tab → Customize"],
  ["Rediscover a bookmark", "One of your older bookmarks, to visit again.", "New tab → Customize"],
  ["Code rain", "Falling green characters, a live wallpaper.", "New tab → Background → Live wallpaper"],
  ["Warp speed", "Fly through the stars.", "New tab → Background → Live wallpaper"],
  ["Bubbles", "Soft bubbles drift up the screen.", "New tab → Background → Live wallpaper"],
  ["Lava lamp", "Slow, glowing blobs.", "New tab → Background → Live wallpaper"],
  ["Constellations", "Points of light that join up as they drift.", "New tab → Background → Live wallpaper"],
  ["Cherry blossoms", "Petals float down across the page.", "New tab → Background → Live wallpaper"]
],
"3.0 · Games": [
  ["Tic-tac-toe", "Against the computer, easy or unbeatable.", "Menu → Games"],
  ["Memory", "Find the eight pairs in as few moves as you can.", "Menu → Games"],
  ["Minesweeper", "Three board sizes; the first click is always safe and right-click flags.", "Menu → Games"],
  ["Breakout", "Clear the wall of bricks over five levels.", "Menu → Games"],
  ["Pong", "First to seven against the computer, at three levels.", "Menu → Games"],
  ["Typing test", "Your words per minute and accuracy in 15, 30 or 60 seconds.", "Menu → Games"],
  ["Reaction time", "Click the moment the box turns green; five tries.", "Menu → Games"],
  ["Aim trainer", "Hit the shrinking targets in 30 seconds.", "Menu → Games"]
],
